import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'

export async function GET(request: NextRequest) {
  console.log('========== AUTH CALLBACK ==========')
  console.log('URL:', request.url)

  const { searchParams, origin } = new URL(request.url)

  // Exchange must happen only in this callback handler.
  const code = searchParams.get('code')

  console.log('Code:', code)

  if (!code) {
    return NextResponse.json({
      success: false,
      message: 'No authorization code received',
      url: request.url,
    })
  }

  try {
    // IMPORTANT:
    // Never redirect with the OAuth query params (code/next). Always go to
    // the clean dashboard URL (no query string).
    const url = new URL('/dashboard', origin)

    // Bind Supabase cookie writes to THIS redirect response.
    // Without this, the cookie mutations performed during the OAuth exchange
    // may not be attached to the response that the browser is receiving
    // immediately after the redirect.
    const redirectResponse = NextResponse.redirect(url)

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return request.cookies.getAll()
          },
          setAll(cookiesToSet: { name: string; value: string; options: CookieOptions }[]) {
            cookiesToSet.forEach(({ name, value, options }) => {
              redirectResponse.cookies.set({ name, value, ...options })
            })
          },
        },
        auth: {
          persistSession: true,
          detectSessionInUrl: false,
        },
      }
    )

    console.log('Exchanging code for session...')

    const { data, error } = await supabase.auth.exchangeCodeForSession(code)

    console.log('Exchange Result:', {
      error,
      hasSession: !!data.session,
      hasUser: !!data.user,
    })

    if (error) {
      return NextResponse.json({
        success: false,
        message: 'exchangeCodeForSession failed',
        error: error.message,
      })
    }

    console.log('Redirecting to:', url.toString())

    // The Set-Cookie headers generated by exchangeCodeForSession are now
    // present on redirectResponse.
    return redirectResponse
  } catch (err: any) {
    console.error('CALLBACK ERROR:', err)

    return NextResponse.json({
      success: false,
      message: err?.message || 'Unknown callback error',
    })
  }
}
