import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)

  // Exchange must happen only in this callback handler.
  const code = searchParams.get('code')

  if (!code) {
    const loginUrl = new URL('/login', origin)
    loginUrl.searchParams.set('message', 'Your login session has expired. Please sign in again.')
    return NextResponse.redirect(loginUrl)
  }

  try {
    // IMPORTANT:
    // Never redirect with the OAuth query params (code/next). Always go to
    // the clean dashboard URL (no query string).
    const url = new URL('/dashboard', origin)

    // Bind Supabase cookie writes to THIS redirect response.
    // Without this, the cookie mutations performed during the OAuth exchange
    // may not be attached to the response that the browser is receiving
    // immediately after the redirect.
    const redirectResponse = NextResponse.redirect(url)

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return request.cookies.getAll()
          },
          setAll(cookiesToSet: { name: string; value: string; options: CookieOptions }[]) {
            cookiesToSet.forEach(({ name, value, options }) => {
              redirectResponse.cookies.set({ name, value, ...options })
            })
          },
        },
        auth: {
          persistSession: true,
          detectSessionInUrl: false,
        },
      }
    )

    const { data, error } = await supabase.auth.exchangeCodeForSession(code)

    if (error) {
      const loginUrl = new URL('/login', origin)
      loginUrl.searchParams.set('message', 'Authentication failed. Please try again.')
      return NextResponse.redirect(loginUrl)
    }

    // The Set-Cookie headers generated by exchangeCodeForSession are now
    // present on redirectResponse.
    return redirectResponse
  } catch (err: any) {
    console.error('CALLBACK ERROR:', err)

    const loginUrl = new URL('/login', origin)
    loginUrl.searchParams.set('message', 'An unexpected authentication error occurred.')
    return NextResponse.redirect(loginUrl)
  }
}
